name: Genera Sfondi Ogni Giorno
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4 # Versione aggiornata

      - name: Installa Python
        uses: actions/setup-python@v5 # Versione aggiornata
        with:
          python-version: '3.12'

      - name: Installa Librerie
        run: pip install requests Pillow

      - name: Esegui lo script
        env:
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          TRAKT_USER: ${{ secrets.TRAKT_USER }}
        # ATTENZIONE: Assicurati che 'crea_cards.py' sia il nome esatto del tuo file!
        run: python crea_cards.py 

      - name: Salva le immagini nel repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sfondi_projectivity/*.jpg || true
          git commit -m "Aggiornamento sfondi del giorno" || exit 0
          git push
