name: Genera Sfondi Ogni Giorno
on:
  schedule:
    - cron: '0 8 * * *' # Scatta ogni mattina alle 8:00
  workflow_dispatch:    # Ti permette di avviarlo a mano con un tasto

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Serve a GitHub per salvare le foto nel repository
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa Librerie
        run: pip install requests Pillow

      - name: Esegui lo script
        env:
          TRAKT_ID: ${{ secrets.TRAKT_ID }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
          TRAKT_USER: ${{ secrets.TRAKT_USER }}
        run: python tuo_script.py # <--- QUI METTI IL NOME DEL TUO FILE .PY

      - name: Salva le immagini nel repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sfondi_projectivity/*.jpg
          git commit -m "Aggiornamento sfondi del giorno" || exit 0
          git push
